TECH_SKILLS: set[str] = {
    "python", "java", "javascript", "typescript", "c", "c++", "c#", "go", "rust", "kotlin",
    "swift", "ruby", "php", "scala", "r", "matlab", "perl", "bash", "powershell", "dart",
    "elixir", "haskell", "lua", "groovy", "clojure", "objective-c", "f#", "fortran", "cobol", "assembly",
    "sql", "postgresql", "mysql", "sqlite", "oracle", "mariadb", "sql server", "mongodb", "cassandra", "redis",
    "dynamodb", "neo4j", "elasticsearch", "opensearch", "clickhouse", "snowflake", "bigquery", "redshift", "hive", "presto",
    "trino", "dbt", "airflow", "kafka", "spark", "flink", "hadoop", "beam", "databricks", "superset",
    "tableau", "power bi", "looker", "tensorflow", "pytorch", "keras", "scikit-learn", "xgboost", "lightgbm", "catboost",
    "numpy", "pandas", "polars", "statsmodels", "opencv", "nltk", "spacy", "hugging face", "langchain", "llamaindex",
    "openai", "anthropic", "vertex ai", "sagemaker", "onnx", "mlflow", "kubeflow", "ray", "dvc", "weights & biases",
    "fastapi", "flask", "django", "starlette", "aiohttp", "express", "nestjs", "react", "next.js", "vue",
    "nuxt", "angular", "svelte", "solidjs", "redux", "zustand", "tailwind css", "bootstrap", "material ui", "chakra ui",
    "graphql", "apollo", "relay", "rest", "grpc", "websocket", "socket.io", "oauth2", "openid connect", "jwt",
    "docker", "kubernetes", "helm", "istio", "terraform", "ansible", "chef", "puppet", "vagrant", "nomad",
    "aws", "azure", "gcp", "ec2", "ecs", "eks", "lambda", "api gateway", "rds", "s3",
    "cloudfront", "route53", "cloudwatch", "iam", "cloudformation", "azure functions", "aks", "cosmos db", "gke", "cloud run",
    "git", "github", "gitlab", "bitbucket", "jenkins", "github actions", "circleci", "travis ci", "argo cd", "spinnaker",
    "prometheus", "grafana", "datadog", "new relic", "sentry", "opentelemetry", "jaeger", "zipkin", "elk", "splunk",
    "linux", "unix", "macos", "windows", "nginx", "apache", "haproxy", "envoy", "consul", "vault",
    "rabbitmq", "celery", "bullmq", "sidekiq", "rasa", "selenium", "playwright", "cypress", "jest", "pytest",
    "vitest", "mocha", "chai", "junit", "testng", "postman", "insomnia", "swagger", "openapi", "protobuf",
    "microservices", "event-driven architecture", "ddd", "tdd", "bdd", "oop", "fp", "design patterns", "clean architecture", "hexagonal architecture",
    "data structures", "algorithms", "system design", "distributed systems", "high availability", "scalability", "caching", "cdn", "rate limiting", "zero trust",
    "encryption", "tls", "mfa", "rbac", "abac", "secrets management", "penetration testing", "owasp", "soc2", "gdpr",
    "etl", "elt", "feature engineering", "a/b testing", "causal inference", "nlp", "computer vision", "recommendation systems", "time series", "bayesian modeling",
}
